name: Build Android
on:
  push:
    branches:
      - master
      - with-navigator
jobs:

  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps: 
      - name: Checkout to Action V2
        uses: actions/checkout@v2

      - name: Checkout Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: |
          npm install

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact APK
        uses: actions/upload-artifact@v2
        with:
          name: RnFootball-apk
          path: android/app/build/outputs/apk/release

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon
          
      - name: Sign App Bundle
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Upload Artifact Bundle
        uses: actions/upload-artifact@v2
        with:
          name: Signed App Bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Deploy to Play Store (BETA)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT }}
          packageName: com.rnfootball
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: beta
          inAppUpdatePriority: 3
          userFraction: 0.5
          whatsNewDirectory: android/release-notes/