name: Build Android
on:
  push:
    branches:
      - master
jobs:

  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps: 
      - name: Checkout to Action V2
        uses: actions/checkout@v2
      - name: Checkout Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RnFootball-apk
          path: android/app/build/outputs/apk/release/app-release.apk